routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('home');
});
*/
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');
/*
Route::get('/user', 'UserController@index');
Route::get('/user-register', 'UserController@create');
Route::post('/user-register', 'UserController@store');
Route::get('/user-edit/{id}', 'UserController@edit');
*/
Route::resource('user', 'UserController');

Route::resource('anggota', 'AnggotaController');

Route::resource('alat', 'AlatController');
Route::get('/format_alat', 'AlatController@format');
Route::post('/import_alat', 'AlatController@import');

Route::resource('transaksi', 'TransaksiController');
Route::get('/laporan/trs', 'LaporanController@transaksi');
Route::get('/laporan/trs/pdf', 'LaporanController@transaksiPdf');
Route::get('/laporan/trs/excel', 'LaporanController@transaksiExcel');

Route::get('/laporan/alat', 'LaporanController@alat');
Route::get('/laporan/alat/pdf', 'LaporanController@alatPdf');
Route::get('/laporan/alat/excel', 'LaporanController@alatExcel');

app/Alat.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alat extends Model
{
    protected $table = 'alat';
    protected $fillable = ['nama_alat', 'jumlah_alat', 'deskripsi', 'foto_alat'];


    /**
     * Method One To Many 
     */
    public function transaksi()
    {
        //return $this->hasMany(Transaksi::class);
        return $this->hasMany('App\Transaksi', 'id');
    }
}

app/Http/Controllers/AlatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Alat;
use Carbon\Carbon;
use Session;
use Illuminate\Support\Facades\Redirect;
use Auth;
use DB;
use Excel;
use RealRashid\SweetAlert\Facades\Alert;

class AlatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        if(Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        $datas = Alat::get();
        
        return view('alat.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->level == 'user') {
            Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
            return redirect()->to('/');
        }

        return view('alat.create');
    }

    public function format()
    {
        $data = [['nama_alat' => null, 'jumlah_alat' => null, 'deskripsi' => null]];
            $fileName = 'format-alat';
            

        $export = Excel::create($fileName.date('Y-m-d_H-i-s'), function($excel) use($data){
            $excel->sheet('alat', function($sheet) use($data) {
                $sheet->fromArray($data);
            });
        });

        return $export->download('xlsx');
    }

    public function import(Request $request)
    {
        $this->validate($request, [
            'importalat' => 'required'
        ]);

        if ($request->hasFile('importalat')) {
            $path = $request->file('importalat')->getRealPath();

            $data = Excel::load($path, function($reader){})->get();
            $a = collect($data);

            if (!empty($a) && $a->count()) {
                foreach ($a as $key => $value) {
                    $insert[] = [
                            'nama_alat' => $value->nama_alat,                          
                            'jumlah_alat' => $value->jumlah_alat, 
                            'deskripsi' => $value->deskripsi, 
                            'foto_alat' => NULL];

                    Alat::create($insert[$key]);
                        
                    }
                  
            };
        }
        alert()->success('Berhasil.','Data telah diimport!');
        return back();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nama_alat' => 'required|string|max:255',
        ]);

        if($request->file('foto_alat')) {
            $file = $request->file('foto_alat');
            $dt = Carbon::now();
            $acak  = $file->getClientOriginalExtension();
            $fileName = rand(11111,99999).'-'.$dt->format('Y-m-d-H-i-s').'.'.$acak; 
            $request->file('foto_alat')->move("images/alat", $fileName);
            $foto_alat = $fileName;
        } else {
            $foto_alat = NULL;
        }

        Alat::create([
                'nama_alat' => $request->get('nama_alat'),
                'jumlah_alat' => $request->get('jumlah_alat'),
                'deskripsi' => $request->get('deskripsi'),
                'foto_alat' => $foto_alat
            ]);

        alert()->success('Berhasil.','Data telah ditambahkan!');

        return redirect()->route('alat.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(Auth::user()->level == 'user') {
                Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
                return redirect()->to('/');
        }

        $data = alat::findOrFail($id);

        return view('alat.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {   
        if(Auth::user()->level == 'user') {
                Alert::info('Oopss..', 'Anda dilarang masuk ke area ini.');
                return redirect()->to('/');
        }

        $data = alat::findOrFail($id);
        return view('alat.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if($request->file('foto_alat')) {
            $file = $request->file('foto_alat');
            $dt = Carbon::now();
            $acak  = $file->getClientOriginalExtension();
            $fileName = rand(11111,99999).'-'.$dt->format('Y-m-d-H-i-s').'.'.$acak; 
            $request->file('foto_alat')->move("images/alat", $fileName);
            $foto_alat = $fileName;

            Alat::find($id)->update([
                'nama_alat' => $request->get('nama_alat'),
                   'jumlah_alat' => $request->get('jumlah_alat'),
                   'deskripsi' => $request->get('deskripsi'),
                   'foto_alat' => $foto_alat
                   ]);
        }

        Alat::find($id)->update([
             'nama_alat' => $request->get('nama_alat'),
                'jumlah_alat' => $request->get('jumlah_alat'),
                'deskripsi' => $request->get('deskripsi'),
                ]);

        alert()->success('Berhasil.','Data telah diubah!');
        return redirect()->route('alat.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Alat::find($id)->delete();
        alert()->success('Berhasil.','Data telah dihapus!');
        return redirect()->route('alat.index');
    }
}

resources/views/alat/create.blade.php
@section('js')

<script type="text/javascript">

$(document).ready(function() {
    $(".users").select2();
});

</script>

<script type="text/javascript">
        function readURL() {
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(input).prev().attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(function () {
            $(".uploads").change(readURL)
            $("#f").submit(function(){
                // do ajax submit or just classic form submit
              //  alert("fake subminting")
                return false
            })
        })
        </script>
@stop

@extends('layouts.app')

@section('content')

<form method="POST" action="{{ route('alat.store') }}" enctype="multipart/form-data">
    {{ csrf_field() }}
<div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
              <div class="row flex-grow">
                <div class="col-12">
                  <div class="card">
                    <div class="card-body">
                      <h4 class="card-title">Tambah Alat baru</h4>
                      
                        <div class="form-group{{ $errors->has('nama_alat') ? ' has-error' : '' }}">
                            <label for="nama_alat" class="col-md-4 control-label">Nama</label>
                            <div class="col-md-6">
                                <input id="nama_alat" type="text" class="form-control" name="nama_alat" value="{{ old('nama_alat') }}" required>
                                @if ($errors->has('nama_alat'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nama_alat') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- <div class="form-group{{ $errors->has('nomor_anggota') ? ' has-error' : '' }}">
                            <label for="penyedia" class="col-md-4 control-label">Penyedia</label>
                            <div class="col-md-6">
                                <input id="penyedia" type="text" class="form-control" name="penyedia" value="{{ old('penyedia') }}" required>
                                @if ($errors->has('penyedia'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('penyedia') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div> --}}
                        
                        
                        
                        <div class="form-group{{ $errors->has('jumlah_alat') ? ' has-error' : '' }}">
                            <label for="jumlah_alat" class="col-md-4 control-label">Jumlah Alat</label>
                            <div class="col-md-6">
                                <input id="jumlah_alat" type="number" maxlength="4" class="form-control" name="jumlah_alat" value="{{ old('jumlah_buku') }}" required>
                                @if ($errors->has('jumlah_alat'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('jumlah_alat') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('deskripsi') ? ' has-error' : '' }}">
                            <label for="deskripsi" class="col-md-4 control-label">Deskripsi</label>
                            <div class="col-md-12">
                                <input id="deskripsi" type="text" class="form-control" name="deskripsi" value="{{ old('deskripsi') }}" >
                                @if ($errors->has('deskripsi'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('deskripsi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                        <div class="form-group">
                            <label for="email" class="col-md-4 control-label">Foto Alat</label>
                            <div class="col-md-6">
                                <img width="200" height="200" />
                                <input type="file" class="uploads form-control" style="margin-top: 20px;" name="foto_alat">
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary" id="submit">
                                    Submit
                        </button>
                        <button type="reset" class="btn btn-danger">
                                    Reset
                        </button>
                        <a href="{{route('alat.index')}}" class="btn btn-light pull-right">Back</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

</div>
</form>
@endsection

resources/views/alat/edit.blade.php
@section('js')

<script type="text/javascript">

$(document).ready(function() {
    $(".users").select2();
});

</script>

<script type="text/javascript">
        function readURL() {
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(input).prev().attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(function () {
            $(".uploads").change(readURL)
            $("#f").submit(function(){
                // do ajax submit or just classic form submit
              //  alert("fake subminting")
                return false
            })
        })
        </script>
@stop

@extends('layouts.app')

@section('content')

<form action="{{ route('alat.update', $data->id) }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{ method_field('put') }}
<div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
              <div class="row flex-grow">
                <div class="col-12">
                  <div class="card">
                    <div class="card-body">
                      <h4 class="card-title">Edit Alat <b>{{$data->nama_alat}}</b> </h4>
                      <form class="forms-sample">
                        <div class="form-group{{ $errors->has('nama_alat') ? ' has-error' : '' }}">
                            <label for="nama_alat" class="col-md-4 control-label">Nama</label>
                            <div class="col-md-6">
                                <input id="nama_alat" type="text" class="form-control" name="nama_alat" value="{{ $data->nama_alat }}" required>
                                @if ($errors->has('nama_alat'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nama_alat') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- <div class="form-group{{ $errors->has('nomor_anggota') ? ' has-error' : '' }}">
                            <label for="penyedia" class="col-md-4 control-label">Penyedia</label>
                            <div class="col-md-6">
                                <input id="penyedia" type="text" class="form-control" name="penyedia" value="{{ $data->penyedia }}" required>
                                @if ($errors->has('penyedia'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('penyedia') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div> --}}
                        <div class="form-group{{ $errors->has('jumlah_alat') ? ' has-error' : '' }}">
                            <label for="jumlah_alat" class="col-md-4 control-label">Jumlah Alat</label>
                            <div class="col-md-6">
                                <input id="jumlah_alat" type="number" maxlength="4" class="form-control" name="jumlah_alat" value="{{ $data->jumlah_alat }}" required>
                                @if ($errors->has('jumlah_alat'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('jumlah_alat') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('deskripsi') ? ' has-error' : '' }}">
                            <label for="deskripsi" class="col-md-4 control-label">Deskripsi</label>
                            <div class="col-md-12">
                                <input id="deskripsi" type="text" class="form-control" name="deskripsi" value="{{ $data->deskripsi }}" >
                                @if ($errors->has('deskripsi'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('deskripsi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        

                        <div class="form-group">
                            <label for="email" class="col-md-4 control-label">Foto Alat</label>
                            <div class="col-md-6">
                                <img width="200" height="200" @if($data->foto_alat) src="{{ asset('images/alat/'.$data->foto_alat) }}" @endif />
                                <input type="file" class="uploads form-control" style="margin-top: 20px;" name="foto_alat">
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary" id="submit">
                                    Update
                        </button>
                        <a href="{{route('alat.index')}}" class="btn btn-light pull-right">Back</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

</div>
</form>
@endsection

resources/views/alat/index.blade.php
@section('js')
<script type="text/javascript">
  $(document).ready(function() {
    $('#table').DataTable({
      "iDisplayLength": 50
    });

} );
</script>
@stop
@extends('layouts.app')

@section('content')
<div class="row">

  <div class="col-lg-2">
    <a href="{{ route('alat.create') }}" class="btn btn-primary btn-rounded btn-fw"><i class="fa fa-plus"></i> Tambah Alat</a>
  </div>
{{-- <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <form action="{{ url('import_alat') }}" method="post" class="form-inline" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="input-group {{ $errors->has('importalat') ? 'has-error' : '' }}">
              <input type="file" class="form-control" name="importalat" required="">

              <span class="input-group-btn">
                              <button type="submit" class="btn btn-success" style="height: 38px;margin-left: -2px;">Import</button>
                            </span>
            </div>
          </form>

        </div> --}}
    <div class="col-lg-12">
                  @if (Session::has('message'))
                  <div class="alert alert-{{ Session::get('message_type') }}" id="waktu2" style="margin-top:10px;">{{ Session::get('message') }}</div>
                  @endif
                  </div>
</div>
<div class="row" style="margin-top: 20px;">
<div class="col-lg-12 grid-margin stretch-card">
              <div class="card">

                <div class="card-body">
                  <h4 class="card-title pull-left">Data Alat</h4>
                  <div class="table-responsive">
                    <table class="table table-striped" id="table">
                      <thead>
                        <tr>
                          <th>
                            Nama Alat
                          </th>
                          <th>
                            Deskripsi
                          </th>                                                    
                          <th>
                            Stok
                          </th>                          
                          <th>
                            Aksi
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                      @foreach($datas as $data)
                        <tr>
                          <td class="py-1">
                          @if($data->foto_alat)
                            <img src="{{url('images/alat/'. $data->foto_alat)}}" alt="image" style="margin-right: 10px;" />
                          @else
                            <img src="{{url('images/alat/default.png')}}" alt="image" style="margin-right: 10px;" />
                          @endif
                          <a href="{{route('alat.show', $data->id)}}" style="color: #76d275;"> 
                            {{$data->nama_alat}}
                          </a>
                          </td>
                          <td>
                          
                            {{$data->deskripsi}}
                          
                          </td>

                          
                          <td>
                            {{$data->jumlah_alat}}
                          </td>
                          
                          <td>
                          <div class="btn-group dropdown">
                          <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Aksi
                          </button>
                          <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                            <a class="dropdown-item" href="{{route('alat.edit', $data->id)}}"> Edit </a>
                            <form action="{{ route('alat.destroy', $data->id) }}" class="pull-left"  method="post">
                            {{ csrf_field() }}
                            {{ method_field('delete') }}
                            <button class="dropdown-item" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                            </button>
                          </form>
                           
                          </div>
                        </div>
                          </td>
                        </tr>
                      @endforeach
                      </tbody>
                    </table>
                  </div>
               {{--  {!! $datas->links() !!} --}}
                </div>
              </div>
            </div>
          </div>
@endsection

resources/views/alat/show.blade.php
@section('js')

<script type="text/javascript">

$(document).ready(function() {
    $(".users").select2();
});

</script>

<script type="text/javascript">
        function readURL() {
            var input = this;
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $(input).prev().attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $(function () {
            $(".uploads").change(readURL)
            $("#f").submit(function(){
                // do ajax submit or just classic form submit
              //  alert("fake subminting")
                return false
            })
        })
        </script>
@stop

@extends('layouts.app')

@section('content')

<div class="row">
            <div class="col-md-12 d-flex align-items-stretch grid-margin">
              <div class="row flex-grow">
                <div class="col-12">
                  <div class="card">
                    <div class="card-body">
                      <h4 class="card-title">Detail <b>{{$data->nama_alat}}</b> </h4>
                      <form class="forms-sample">

                        <div class="form-group">
                            <div class="col-md-6">
                                <img width="200" height="200" @if($data->foto_alat) src="{{ asset('images/alat/'.$data->foto_alat) }}" @endif />
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('nama_alat') ? ' has-error' : '' }}">
                            <label for="nama_alat" class="col-md-4 control-label">Nama</label>
                            <div class="col-md-6">
                                <input id="nama_alat" type="text" class="form-control" name="nama_alat" value="{{ $data->nama_alat }}" readonly="">
                                @if ($errors->has('nama_alat'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('nama_alat') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        {{-- <div class="form-group{{ $errors->has('npm') ? ' has-error' : '' }}">
                            <label for="penyedia" class="col-md-4 control-label">Penyedia</label>
                            <div class="col-md-6">
                                <input id="penyedia" type="text" class="form-control" name="penyedia" value="{{ $data->penyedia }}" readonly>
                                @if ($errors->has('penyedia'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('penyedia') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>                                                                         --}}
                        <div class="form-group{{ $errors->has('jumlah_alat') ? ' has-error' : '' }}">
                            <label for="jumlah_alat" class="col-md-4 control-label">Jumlah Alat</label>
                            <div class="col-md-6">
                                <input id="jumlah_alat" type="number" maxlength="4" class="form-control" name="jumlah_alat" value="{{ $data->jumlah_alat }}" readonly>
                                @if ($errors->has('jumlah_alat'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('jumlah_alat') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('deskripsi') ? ' has-error' : '' }}">
                            <label for="deskripsi" class="col-md-4 control-label">Deskripsi</label>
                            <div class="col-md-12">
                                <input id="deskripsi" type="text" class="form-control" name="deskripsi" value="{{ $data->deskripsi }}" readonly="">
                                @if ($errors->has('deskripsi'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('deskripsi') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        


                        <a href="{{route('alat.index')}}" class="btn btn-light pull-right">Back</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>

</div>
@endsection